### ISSUE TITLE
Selecting "Use exact taxonomic level:" to "No" disconnects server

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBEnrich#2]

**Comment by sdgamboa** [comment]
I think this bug is in bugsigdbr. See https://github.com/waldronlab/bugsigdbr/issues/60

**Comment by sdgamboa** [comment]
This commit [b278df5](https://github.com/waldronlab/BugSigDBEnrich/commit/b278df5fb6144fce461d4c8b9def63d9c4a3104e) should fix the problem by preventing users from selecting "No" with more than one taxonomic rank.
